### ISSUE TITLE
Write an introduction to testing at W3C

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#1]
This should explain the different kins of tests.

**Comment by hubenjamin** [comment]
Draft finished and pull request submitted

**Comment by tobie** [comment]
Added a bunch of comments in the issue tracker.

I have a feeling you probably want to write that one last, when we have a better idea of where we're going with the whole doc site.

**Comment by hubenjamin** [comment]
OK, agree to hold it on until we finish the whole doc site. If we didn't try, we don't know it actually should be the last one.
