### ISSUE TITLE
Documentation on CLA verification

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#10]
From the perspective of reviewers. We should use CLAHub or somesuch.

**Comment by hubenjamin** [comment]
Do you mean the reviewer to verify himself? Or verify others? My initial draft is to verify himself - go to the same CLAHub link, and it will show you. If you mean to verify others, how are we doing this today? Thanks

**Comment by tobie** [comment]
There is no up and running solution for this atm. Right now, we should be documenting the existing process (which doesn't use CLAHub), which afaik has already been described in some of the resources.

**Comment by tobie** [comment]
This needs to describe the new process explained here: http://lists.w3.org/Archives/Public/public-test-infra/2013JulSep/0071.html
