### ISSUE TITLE
Documentation on how to sign the CLA

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#11]
From the perspective of test writers. We should use CLAHub or somesuch.

**Comment by hubenjamin** [comment]
Current webapps process http://www.w3.org/wiki/Webapps/Submitting_tests#How_to_Submit_a_New_Test_-_The_Short_Version says to sign W3C's License Grant Form http://www.w3.org/2002/09/wbs/1/testgrants2-200409/, if employer is not a member and you have not done this before. In another words, if your employer is a member, you don't need to sign anything. Any other thoughts?
