### ISSUE TITLE
Fix the title 'communication channels' 

### ISSUE THREAD

**Issue by rhauck** [w3c/testtwf-website#110]
Too long. Should be 'Contact' or something more engaging and inviting. Could brainstorm on this a little.

**Comment by tobie** [comment]
`talk-to-other-humans` ?
`say-hello` ?
`hello` ?
`hi` ?

let's not be too clever though Thinks just `Contact` should be fine.

**Comment by rhauck** [comment]
I was thinking something like 'Yo, Hit Us Up'.  But 'Contact' is good, too.  

Another (serious) suggestion would be 'Ask' - with a very inviting message at the top of the page that questions are welcome in any of these channels.

**Comment by tobie** [comment]
I like `ask`.

**Comment by tobie** [comment]
I went for `discuss` (mostly because I didn't have access to this conversation as I was offline). Feel free to change. 

ref. commit: 0a75334ee6700b35957312765b458f2d22c5c338
