### ISSUE TITLE
Documentation for the bug reporting process

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#12]
Normal GitHUB workflow, use issues.

**Comment by hubenjamin** [comment]
Spec bug? or bug of UA implementation? Or bug of test suite itself? Spec bug is tracked by Bugzilla. Which tool are we using today to report vendor's UA implementation bug? to report test suite bug? Thanks

**Comment by tobie** [comment]
Those are good points. Probably all three. With a clear explanation of what to do what when. Again I've seen resources on this in the TTWF folder.
