### ISSUE TITLE
Documentation for the test submission process

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#14]
E.g. based on the WebApps wiki.

Also, great resource on [ttwf.org](http://testthewebforward.org/resources/github_test_submission.html).

**Comment by hubenjamin** [comment]
PR #38, commit hubenjamin@01fcff66a7a6cf11279561d0c81810777ee9e422, and based on WebApps' process http://www.w3.org/wiki/Webapps/Submitting_tests#How_to_Submit_a_New_Test_-_The_Short_Version. Please note that this issue topic may overlap with issue #29, which address the same topic but based on http://testthewebforward.org/resources/github_test_submission.html.
