### ISSUE TITLE
Change structure of address lines in YAML front end to let markdown format them

### ISSUE THREAD

**Issue by rhauck** [w3c/testtwf-website#144]
"if it works"

See discussion:
https://github.com/w3c/testtwf-website/pull/138#discussion_r6645103

**Comment by rhauck** [comment]
Tried several things with no luck.  Tried:
location:
(indented)     address: |
       (indented x 2)  XXX
        (indented x 2) XXX

Tried the same with '>' instead of '|'

Tried plain old markdownify and with the above two syntaxes.   I'm out of ideas.

**Comment by tobie** [comment]
:(

That indeed doesn't seem to work (the YAML eats the line break away).

So your choice boils down to:

```
line 1<br>line 2
```

```
line 1\nline 2
```

(will need replacing `\n` by `<br>`.)

```
["line 1", "line 2"]
```

Your pick.

**Comment by rhauck** [comment]
The third option is what's there now (with the additional address info added, which is the PR that's currently staged from your repo).   I guess I pick that one since I already did. :)

**Comment by tobie** [comment]
Heh. Yeah. Sorry for wasting your time with this. The end solution is ugly, but it seems we can do no better. :(

**Comment by rhauck** [comment]
ok, I'll close this then.
