### ISSUE TITLE
Add a place for microblogging links

### ISSUE THREAD

**Issue by rhauck** [w3c/testtwf-website#151]
When Register button moved to the top of the page, we lost the place for Twitter/Weibo links. We need to add it back, but it's not obvious where.

**Comment by tobie** [comment]
Would suggest doing something site-wide, in the sidebar.

**Comment by rhauck** [comment]
I was thinking the same for at least the event pages, but should we also try to have it on the docs & blog sections of the site? Also how do we handle Weibo vs. Twitter?

**Comment by tobie** [comment]
I would have twitter (+ Weibo) in blog + events, probably not in the docs.
