### ISSUE TITLE
Need a doc for how to interpret a spec into a test 

### ISSUE THREAD

**Issue by rhauck** [w3c/testtwf-website#163]
We have been giving a version of this talk at almost all of the TestTWF events and I think it should be documented here as well.  Doc should cover testable assertions, RFC-2119, propdefs, etc.

**Comment by rhauck** [comment]
This is a good reference:
Slides 3-10:  http://w3c.github.io/testing-how-to/#(3)

**Comment by tobie** [comment]
Closing as dup of #20.
