### ISSUE TITLE
Documentation on manual tests and when those are appropriate

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#17]
E.g. based Dzenana Trenutak's [work](http://dzenana-trenutak.github.com/GitDocs/W3C_HTMLTestsuite_Tutorial/index.html).

**Comment by hubenjamin** [comment]
If "Let's completely avoid the whole manual testing thing for now" as commented in Issue-1, should it be part of Reftest documentation? Or do we still need to document the guidance on Manual Tests? Thanks

**Comment by hubenjamin** [comment]
BTW, Dzenana Trenutak's work link gives a 404 error. Thanks

**Comment by tobie** [comment]
> If "Let's completely avoid the whole manual testing thing for now" as commented in Issue-1, should it be part of Reftest documentation?

No.

> Or do we still need to document the guidance on Manual Tests?

Not yet. We'll be using WebDriver for this, and this needs a lot more work before we're ready to get folks writing tests.

**Comment by tobie** [comment]
> BTW, Dzenana Trenutak's work link gives a 404 error. Thanks

Yup. Found the right link by looking at the root of the link. Fixed.
