### ISSUE TITLE
Add bio for Daniel Davis

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#248]
/cc @tagawa

In: https://github.com/w3c/testtwf-website/blob/gh-pages/_config.yml#L252-L254

You're missing a bio similar to:

https://github.com/w3c/testtwf-website/blob/gh-pages/_config.yml#L509

**Comment by tagawa** [comment]
Thanks - just sent a PR: https://github.com/w3c/testtwf-website/pull/249
