### ISSUE TITLE
Document how to work with GitHub

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#29]
There's doc on this somewhere, probably in the TTWF resources.

**Comment by marcoscaceres** [comment]
What in particular do you want to document here?

**Comment by tobie** [comment]
Github 101. I think @rhauck has some good content here: http://testthewebforward.org/resources/github_test_submission.html

**Comment by lmclister** [comment]
fyi localized into JP at http://testthewebforward.org/jp/resources/github_test_submission.html

**Comment by hubenjamin** [comment]
Finished and pull request sent

**Comment by tobie** [comment]
@hubenjamin, GitHub lets you [cross-link issues and pull requests](https://help.github.com/articles/github-flavored-markdown#references).

**Comment by hubenjamin** [comment]
PR #35 with most recent commit hubenjamin@6381666ca8c2dd7afed7fa6eda7b36e9a8b65bad.

**Comment by hubenjamin** [comment]
Most recent commit hubenjamin@5ad67610c9a6d145201bf3a902a512a9dc31b0ed in PR #35.
