### ISSUE TITLE
Pics of experts that need to be fetched and added to /assets/experts dir

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#47]
This is made slightly more difficult because the twitter API changed.
- [x] Alan Stearns: http://api.twitter.com/1/users/profile_image/alanstearns?size=normal
- [x] Alex Danilo: http://api.twitter.com/1/users/profile_image/alexanderdanilo?size=normal
- [x] Ally Ogilvie: http://api.twitter.com/1/users/profile_image/testthewebfwd?size=normal
- [x] Arron Eicholz: http://api.twitter.com/1/users/profile_image/MrCSS?size=normal
- [x] Brett Morgan: https://lh5.googleusercontent.com/-WfJyK9PSyBY/AAAAAAAAAAI/AAAAAAAACYI/yUxeUFI5ogU/s250-c-k/photo.jpg
- [x] Brian Birtles: http://m3.licdn.com/mpr/pub/image-X54r703CmoUBGwhRZJ6i8Et-qlK5l1V_XABe8NAhqSrjQiGuX54e28eCqwzxIMX7Tr54/brian-birtles.jpg
- [x] Cameron McCormack: http://api.twitter.com/1/users/profile_image/heycam?size=normal
- [x] Chris Lilley: http://api.twitter.com/1/users/profile_image/svgeesus?size=normal
- [x] Cyril Concolato: http://api.twitter.com/1/users/profile_image/cconcolato?size=normal
- [x] Daniel Glazman: http://api.twitter.com/1/users/profile_image/glazou?size=normal
- [x] Darryl Cain: https://lh4.googleusercontent.com/-TV51Z6ajTZA/AAAAAAAAAAI/AAAAAAAAa08/mXLc5O0Kjcs/s250-c-k/photo.jpg
- [x] Dave Methvin: http://api.twitter.com/1/users/profile_image/davemethvin?size=normal
- [x] David Rousset: http://api.twitter.com/1/users/profile_image/davrous?size=normal
- [x] Dirk Schulze: http://api.twitter.com/1/users/profile_image/dirkschulze?size=normal
- [x] Dmitry Baranovskiy: http://api.twitter.com/1/users/profile_image/DmitryBaranovsk?size=normal
- [x] Doug Schepers: http://www.w3.org/People/Schepers/schepers-fez-small.png
- [x] Eiji Kitamura: http://api.twitter.com/1/users/profile_image/agektmr?size=normal
- [x] Emil A.Eklund: http://api.twitter.com/1/users/profile_image/eae?size=normal
- [x] Erik Dahlström: http://api.twitter.com/1/users/profile_image/erikdahlstrom?size=normal
- [ ] Glenn Adams: http://www.gravatar.com/avatar/143aa32bc3304755c428bcc83704cb12
- [ ] Ido Green: http://api.twitter.com/1/users/profile_image/greenido?size=normal
- [ ] Jacob Goldstein: http://api.twitter.com/1/users/profile_image/JacobG415?size=normal
- [ ] Jacob Rossi: http://api.twitter.com/1/users/profile_image/jacobrossi?size=normal
- [ ] Jared Wyles: http://api.twitter.com/1/users/profile_image/rioter?size=normal
- [ ] Jeremie Patonnier: http://api.twitter.com/1/users/profile_image/JeremiePat?size=normal
- [ ] John Allsopp: http://johnfallsopp.com/images/johnrnd.png
- [ ] John Jansen: http://api.twitter.com/1/users/profile_image/thejohnjansen?size=normal
- [ ] Kensaku Komatsu: http://api.twitter.com/1/users/profile_image/komasshu?size=normal
- [ ] Koji Ishii: http://api.twitter.com/1/users/profile_image/kojiishi?size=normal
- [ ] L. David Baron: https://si0.twimg.com/profile_images/1605345343/david-2011-09-13-by-nitot-square.jpg
- [ ] Levi Weintraub: http://api.twitter.com/1/users/profile_image/levidub?size=normal
- [ ] Masahito Kawamori: http://api.twitter.com/1/users/profile_image/testthewebfwd?size=normal
- [ ] Masataka Yakura: http://api.twitter.com/1/users/profile_image/myakura?size=normal
- [ ] Michael Brooks: http://api.twitter.com/1/users/profile_image/mwbrooks?size=normal
- [ ] Michael[tm] Smith: http://api.twitter.com/1/users/profile_image/sideshowbarker?size=normal
- [ ] Mike West: http://api.twitter.com/1/users/profile_image/mikewest?size=normal
- [ ] Oli Studholme: http://api.twitter.com/1/users/profile_image/boblet?size=normal
- [ ] Peter Linss: undefined
- [ ] Philip Rogers: https://lh4.googleusercontent.com/-vX4CsIkmKBM/Tgvr4_iyqPI/AAAAAAAAAIk/TvLJpsf5oLw/s403/264239_686938568152_71108931_34779783_1600281_s.jpg
- [ ] Rebecca Hauck: http://api.twitter.com/1/users/profile_image/RebeccaHauck?size=normal
- [ ] Rik Cabanier: http://api.twitter.com/1/users/profile_image/rcabanier?size=normal
- [ ] Robin Berjon: http://api.twitter.com/1/users/profile_image/robinberjon?size=normal
- [ ] Ryosuke Niwa: http://api.twitter.com/1/users/profile_image/RyosukeNiwa?size=normal
- [ ] Shinyu Murakami: http://api.twitter.com/1/users/profile_image/MurakamiShinyu?size=normal
- [ ] Silvia Pfeiffer: http://api.twitter.com/1/users/profile_image/silviapfeiffer?size=normal
- [ ] Simon Pieters: http://api.twitter.com/1/users/profile_image/zcorpan?size=normal
- [ ] Simon Sapin: http://api.twitter.com/1/users/profile_image/SimonSapin?size=normal
- [ ] Sylvain Galineau: http://api.twitter.com/1/users/profile_image/sgalineau?size=normal
- [ ] Tim Ansell: https://lh5.googleusercontent.com/-BpWMMwSIuj4/AAAAAAAAAAI/AAAAAAAACsI/Xg_CMs0JTWo/s250-c-k/photo.jpg
- [ ] Tobie Langel: http://api.twitter.com/1/users/profile_image/tobie?size=normal
- [ ] Tomomi Imura: http://api.twitter.com/1/users/profile_image/girlie_mac?size=normal
- [ ] Vincent Hardy: http://api.twitter.com/1/users/profile_image/vincent_hardy?size=normal
- [ ] fantasai: http://static.sched.org/a/160131/avatar.jpg.75x75px.jpg

**Comment by lmclister** [comment]
I'm current fixing this mess on the live site, so I can take this one on as well.

**Comment by tobie** [comment]
Awesome.
