### ISSUE TITLE
Page on where to ask for help

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#7]
This effort should aim to consolidate the different channels or clearly label them if they need to co-exist (e.g. serve different needs).

**Comment by hubenjamin** [comment]
Any idea of what is our official channel of Help? public-test-infra@ mailing list? a dedicated blog forum? a dedicated IRC channel? Thanks

**Comment by tobie** [comment]
Actually, I don't think there's agreement here. And this probably needs reconciling various irc channels and mailing lists.

It might also be valuable to compile a list of related working group mailing lists (some have dedicated lists for testing).

Think your best bet here is to take this to public-infra and start a thread on the topic.

You might also want to reach out to the TTWF folks (@rhauck, @lmclister) to see what kind of expectations they've setup when signing folks to the ttwf mailing list (whatever the exact address is.

**Comment by tobie** [comment]
Related irc channels: #htmlt, #test, #testing

**Comment by hubenjamin** [comment]
I extracted and documented current testing related discussion channels, and just initiated the discussion in public-test-infra mailing list. Hopefully there will be a solution through discussion.

**Comment by tobie** [comment]
Awesome. Link to post? Hasn't come my way yet.

**Comment by hubenjamin** [comment]
Hold on, dealing with branching details etc, and will go your way soon.

**Comment by tobie** [comment]
Sorry, meant to [mailing list post](http://lists.w3.org/Archives/Public/public-test-infra/2013AprJun/0067.html).

**Comment by hubenjamin** [comment]
Sometimes the mailing list is very slow. BTW, I have documented those resources. Do you want to preview it? or hold on until we have conclusion in mailing list?

**Comment by tobie** [comment]
Yeah, just send a pull request. We can always fix them later.

**Comment by hubenjamin** [comment]
Just sent you the pull request from my "issue7" branch, and file is "issue7-help.md". Thanks

**Comment by tobie** [comment]
Your master branch is still kind of screwed up with lots of junk. Sent you explanation on how to fix this.

**Comment by hubenjamin** [comment]
I renamed it to "help-resources.md", and waiting for your explanation (through email, I assume) to clean up master branch. Or should I just checkout master, rm those old junks, and commit and push to my origin?

**Comment by tobie** [comment]
See my comments on the pull request itself for instructions on how to fix your git repo.

**Comment by tobie** [comment]
Here: https://github.com/w3c/ttwf-docs/pull/30#issuecomment-18876263

**Comment by hubenjamin** [comment]
I resent the pull request after doing it according to your instruction. But in my gh-pages, those old files are still visible. So I did the following:

git checkout gh-pages
git rm <those old 4 files>
git commit
git push origin gh-pages

Those old 4 files are gone in my gh-pages branch.

Now my issue7 branch and discussion branch has the new "help-resources.md", but gh-pages and master branch only has the files forked from your site.

**Comment by hubenjamin** [comment]
I deleted my old repository and re-forked a clean version. From there, I set up branch "issue7" and committed "help-resources.md". I just sent you a pull request with only this commit there. Hopefully this time it works. Thanks
