### ISSUE TITLE
Migrate page for Shanghai event from live site to this one

### ISSUE THREAD

**Issue by tobie** [w3c/testtwf-website#71]
This implies moving the content from `http://testthewebforward.org/events/shanghai-2013.html` to `/events/2013/shanghai.md`.

This also implies redirecting `/events/shanghai-2013.html` to `/events/2013/shanghai.html` using the redirect template.

**Comment by rhauck** [comment]
Just realized it didn't do the redirect.  Reopening & I'll take care of it shortly.
